repos:
  - repo: https://github.com/pycqa/flake8
    rev: 7.1.0
    hooks:
      - id: flake8
        name: flake8 (PEP8 only on src/)
        files: ^src/
        args:
          - --select=E,W
          - --max-line-length=120
